import { Computer, ComputerOptions } from "./computer";
import { SimulatorError } from "./error";
import type { EventGenerator, SimulatorEvent } from "./events";

export class Simulator {
  #computer: Computer = new Computer({
    program: { data: [], instructions: [] },
    devices: "pio-switches-and-leds",
    data: "clean",
  });
  #cpuGenerator: EventGenerator = this.#computer.cpu.run();

  /**
   * Loads a program into the computer!
   * @param options.program The program to load.
   * @param options.data Whether to leave all data (memory, registers, etc.) `unchanged`, `randomize` it or `clean` it.
   * @param options.devices Which devices to connect to the computer.
   */
  loadProgram(options: Omit<ComputerOptions, "previous">) {
    this.#computer = new Computer({ ...options, previous: this.#computer });
    this.#cpuGenerator?.return();
    this.#cpuGenerator = this.#computer.cpu.run();
  }

  /**
   * Returns a copy of the current state of the computer as a JSON object.
   */
  getComputerState() {
    return this.#computer?.toJSON() || null;
  }

  /**
   * Advances the CPU one micro-operation.
   *
   * Also, accepts an optional parameter `extra` that can be used to pass data to the CPU.
   * For instance, after a "computer:read" event, it needs to be a Byte<8>.
   *
   * @param [extra] Any extra data to pass to the CPU.
   * @returns The event that was generated by the Simulator, which could be from *any* device.
   */
  advanceCPU(extra?: unknown): SimulatorEvent {
    if (!this.#computer) throw new SimulatorError("no-program");

    const { value, done } = this.#cpuGenerator!.next(extra);
    if (done) throw new Error("Called advanceCPU on a finished CPU!");

    return value;
  }

  /**
   * Returns an object with all the devices of the computer
   * that can be interacted with from the outside.
   */
  get devices() {
    if (!this.#computer) throw new Error("No computer loaded!");

    return {
      clock: { tick: () => this.#computer.io.clock.tick() },
      console: { clear: () => this.#computer.io.console.clear() },
      f10: { press: () => this.#computer.io.f10.press() },
      printer: {
        connected: () => "printer" in this.#computer.io,
        clear: () => {
          if ("printer" in this.#computer.io) return this.#computer.io.printer.clear();
          else console.warn("No printer connected to the computer!");
        },
        print: () => {
          if ("printer" in this.#computer.io) return this.#computer.io.printer.print();
          else console.warn("No printer connected to the computer!");
        },
      },
      switches: {
        connected: () => "printer" in this.#computer.io,
        toggle: (index: number) => {
          if ("switches" in this.#computer.io) return this.#computer.io.switches.toggle(index);
          else console.warn("No switches connected to the computer!");
        },
      },
    };
  }
}

export type { ComputerOptions, SimulatorEvent };
export { SimulatorError };
